# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"4\n\x04Time\x12\x0c\n\x04hour\x18\x01 \x02(\x05\x12\x0e\n\x06minute\x18\x02 \x02(\x05\x12\x0e\n\x06second\x18\x03 \x02(\x05\"P\n\nsensordata\x12\x12\n\ntemprature\x18\x01 \x02(\x02\x12\x14\n\x0cpublisher_id\x18\x02 \x02(\t\x12\x18\n\ttimestamp\x18\x03 \x02(\x0b\x32\x05.Time')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIME._serialized_start=16
  _TIME._serialized_end=68
  _SENSORDATA._serialized_start=70
  _SENSORDATA._serialized_end=150
# @@protoc_insertion_point(module_scope)



